FROM registry.pupgizmo.com/alpine/alpine:3.18

ARG ADOPTIUM_URL=https://packages.adoptium.net/artifactory

RUN apk upgrade --no-cache && \
    wget -O /etc/apk/keys/adoptium.rsa.pub ${ADOPTIUM_URL}/api/security/keypair/public/repositories/apk && \
    echo "${ADOPTIUM_URL}/artifactory/apk/alpine/main" >> /etc/apk/repositories && \
    apk add --no-cache temurin-21-jdk

