FROM registry.pupgizmo.com/ubi/ubi9:latest 

ARG ADOPTIUM_URL=https://packages.adoptium.net/artifactory

RUN curl -fSL https://raw.githubusercontent.com/gizmohundur/repofiles/main/rhel/adoptium-repo-setup | bash && \
    dnf install -y temurin-8-jre git wget zip gzip tar procps && \
    dnf clean all