FROM registry.pupgizmo.com/ubi/ubi9:latest 

ARG ADOPTIUM_URL=https://packages.adoptium.net/artifactory

RUN cat >> /etc/yum.repos.d/adoptium.repo < EOF \
[Adoptium] \
name=Adoptium \
baseurl=${ADOPTIUM_URL}/rpm/rhel/\$releasever/\$basearch \
enabled=1 \
gpgcheck=1 \
gpgkey=${ADOPTIUM_URL}/api/gpg/key/public \
EOF  

RUN dnf install -y temurin-21-jdk git wget zip gzip tar procps && \
    dnf clean all 