FROM registry.access.redhat.com/ubi9/ubi:latest

ARG ADOPTIUM_URL=https://packages.adoptium.net/artifactory

RUN curl -fSL https://raw.githubusercontent.com/gizmohundur/repofiles/main/rhel/adoptium-repo-setup | bash && \
    dnf install -y temurin-21-jdk git wget zip gzip tar procps && \
    dnf clean all 